package lexical_analysis;

public enum TokenType {

    BOOLEAN, INT, LONG, STRING,
    FLOAT, DOUBLE, VOID, CHAR,

    STRING_CONST, CHAR_CONST,
    INTEGER_CONST, REAL_CONST, BOOLEAN_CONST,

    ADD_OP, SUB_OP,
    MUL_OP, DIV_OP,
    INC_OP, DEC_OP,
    POW_OP, MOD_OP,
    AND_OP, OR_OP, XOR_OP,
    LEFT_OP, RIGHT_OP,
    LT_OP, GT_OP,
    LE_OP, EQ_OP,
    GE_OP, NE_OP,
    LOG_AND_OP, LOG_OR_OP, LOG_NEG,

    ASSIGN, MUL_ASSIGN, DIV_ASSIGN,
    MOD_ASSIGN, ADD_ASSIGN, SUB_ASSIGN,
    LEFT_ASSIGN, RIGHT_ASSIGN, POW_ASSIGN,
    AND_ASSIGN, XOR_ASSIGN, OR_ASSIGN,

    L_PAREN, R_PAREN,

    COMMA, DOT,
    COLON, QUESTION_MARK,

    PACKAGE, IMPORT,
    CLASS, INTERFACE, ENUM,
    IMPLEMENTS, EXTENDS,

    LET, FUNCTION, BE,

    PUBLIC, PRIVATE, PROTECTED,
    ABSTRACT, STATIC, FINAL,
    SUPER,

    BREAK, CONTINUE, RETURN,
    IF, ELSE,
    SWITCH, CASE, DEFAULT,
    WHILE, FOR, DO,

    TRY, CATCH,
    THROW, THROWS,

    THIS, NEW,

    ID,

    EOF,EOL, END

}
